### ISSUE TITLE
Extension still actively maintained?

### ISSUE THREAD

**Issue by sluc23** [leftjoinlabs/com.leftjoinlabs.restlog#3]
Hi @seancolsen, this extension is very useful, but it looks like little bit outdated and not under active maintenance.
Are you still maintaining this? or would you like if we could co-maintain it to updated to latest CiviCRM's standards?

great work!

**Comment by seancolsen** [comment]
Hi @sluc23 No, I'm not maintaining it and would love to pass it on to you.

I created Left Join Labs with the hope of developing CiviCRM extensions but then decided to go a different direction. I'd actually like to dismantle the Left Join Labs brand as well by taking the website offline and deleting the GitHub organization, which would leave this repo without a home. Plus there's the issue of the extension key. Would be up for cloning this project to a new one like `com.ixiam.restlog` that you could maintain?

**Comment by sluc23** [comment]
I will start the process of getting ownership of the extension in civicrm.org, plus I think I'll move it to lab.civicrm.org under the canonical name of `apirestlog`. I'll add your reference as creator in the README as well for the great work you did here. 
thanks @seancolsen

**Comment by sluc23** [comment]
https://lab.civicrm.org/extensions/apirestlog
